### ISSUE TITLE
Improve the syncHash() function in grecha.js

### ISSUE THREAD

**Issue by flexiworld** [tsoding/grecha.js#8]
The code can be improved by using the replaceChildren method, which is designed for exactly this kind of scenario—replacing all child nodes of an element with a new set of nodes. Here's how the code can be modified:

Replace the while loop with:

`result.replaceChildren(routes[hashLocation]());`

This single line replaces all child nodes of the result element with the content generated by `routes[hashLocation]()`. This is more concise and achieves the same result as the previous while loop and appendChild combination. It's generally a cleaner and more modern way of updating the content of an element.

**Comment by rexim** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by rexim** [comment]
Resolved by #9
